services:
  burger:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/burger.db
      - FOURM_URL=https://4orm.harrhy.xyz
      - FOURM_CLIENT_ID=burger
      - BURGER_URL=https://big.burger.beauty
